### PR TITLE
README: Fix demo URL

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Btw, http://article-extractor.thomastuts.com/parse?url=http://paulgraham.com/altair.html has an error – is that supposed to happen?

**Comment by thomastuts** [comment]
Nope, still need to add a lot of error handling. Since the module is very early stage, there's pretty much no error handling yet. Will be implemented soon enough!

**Comment by mathiasbynens** [comment]
No worries, I was just wondering because `http://paulgraham.com/altair.html` is the example used in the README.

**Comment by thomastuts** [comment]
Thanks for the heads up, should be fixed now!

**Pull request merged**
